### ISSUE TITLE
Cannot get feedback from SONOS player / group / household

### ISSUE THREAD

**Issue by JoeWiseman** [hklages/node-red-contrib-sonos-events#6] opened 2021-05-31 16:06 UTC
Hi,

I'm trying to get changing states from my SONOS system. Using node SONOS-plus is running fine on Redmatic / CCU3.
So I installed the packed on Redmatic and build a flow just with an event-node. At first I've add new server: ip & port unchanged, name: houshold. After this I entered the static IP of one of my SONOS player. As output I select "ZoneGroupTopology allGroups". (this is "exactly" the flow given in the examples). To validate I connect a debug node which gives the whole msg-object as an output. When deploying everything seems to be ok (node shows "connected 6329") ... but nothing happens ...
![grafik](https://user-images.githubusercontent.com/23559952/120219242-3308b600-c23b-11eb-9eec-1f3078f9e9c9.png)

![grafik](https://user-images.githubusercontent.com/23559952/120219110-fdfc6380-c23a-11eb-8e5f-1becb9c9178b.png)

So I thought about playing around a bit: New node, new server (ip & port unchanged, name: player), IP of the player, ouput "AVTransport content: track, album, title ....". Adding debug-node, deploy .... but still nothing happens :-(
![grafik](https://user-images.githubusercontent.com/23559952/120219193-208e7c80-c23b-11eb-99e4-556c0683d406.png)

![grafik](https://user-images.githubusercontent.com/23559952/120219074-f341ce80-c23a-11eb-9c0c-010961bd54ec.png)

Note: the search-button wihtin the node to find my player isn't working ... So used a port-scanner (https://www.heise.de/download/product/portscan-70308/download) to test the ports on my player. But they does not seem to be open...
![grafik](https://user-images.githubusercontent.com/23559952/120218699-6d258800-c23a-11eb-8ce2-18f49b577c40.png)

Would be great to get some help!

Regards
Joe

**Comment by hklages** [comment] 2021-05-31 16:26
Hi, please send a screenshot of config node household and your CCU firewall settings

**Comment by JoeWiseman** [comment] 2021-05-31 18:09
Hi,
thanks for answering so fast....
here is the configuration-dialog:
![grafik](https://user-images.githubusercontent.com/23559952/120228769-1a54cc00-c24c-11eb-8397-4d37294bb3c4.png)

**Comment by hklages** [comment] 2021-05-31 18:16
Household config node is ok. Did you open port 6329 in firewall settings in CCU?

**Comment by JoeWiseman** [comment] 2021-05-31 18:40
Great! Opening port 6329 on CCU fixet it! Thought it would be ok because of the green message "6329 connected".
Thanks a lot.

Do you have any suggestion for the searching-problem? I've tried to open the port 1900 on the CCU as well, but it was not successful.

Regrads
Joe

**Comment by hklages** [comment] 2021-05-31 19:11
6329:  good to hear. 
Please be aware that it is recommended to only use one config node (household) - see your screenshot with second one "player".  It makes sense to delete that config node and instead use household.

searching: It works on many systems but unfortunately not on Redmatic. I don't know what the problem ist. 

I close this issue. If you need further help feel free to open a new issue.

**Closed as completed by hklages** 2021-05-31 19:11 UTC
Labels: documentation, solved
